### ISSUE TITLE
Load actual config.schema.yml into pi_mqtt_gpio/__init__.py

### ISSUE THREAD

**Issue by a-x-** [flyte/mqtt-io#174]
**Is your feature request related to a problem? Please describe.**
Currently contributors used to change the same config 2 times

**Describe the solution you'd like**
Load actual file instead of `CONFIG_SCHEMA = yaml.safe_load("""`.
Perform any transformations if they required.

**Describe alternatives you've considered**
continue change config 2 times, suffer, forget to sync changes; stop to using the pi-mqtt-gpio

**Comment by flyte** [comment]
Yeah, this is annoying, sorry about that! Although I've changed this in the asyncio version in `feature/asyncio`. Feel free to give that a try. It's pretty much compatible with existing configs.

I don't plan on fixing it on this version of the code, since I'm releasing the async version soon, so I'll close this issue.

**Comment by flyte** [comment]
Instructions for testing out the asyncio version are in https://github.com/flyte/pi-mqtt-gpio/issues/141
