### ISSUE TITLE
Status topic

### ISSUE THREAD

**Issue by amirandap** [flyte/mqtt-io#41]
How can i get the status topic for a specific gpio? The  "status_topic: status" seems to always return running

**Comment by vontrapp** [comment]
The status topic is an MQTT LWT message. This means that the mqtt broker, not the raspberry, will update this message if/when the raspberry disconnects.

To get the status of a specific GPIO, try publishing with the retain option

```
digital_inputs:
  - name: inputx
    ...
    retain: yes

```

Then, the broker will always store the last updated state of that input, and any new subscriber will get that status.

The new subscriber should also check the LWT message from the status_topic, because if that reports that the raspberrypi is not running, then the value of the gpio topic may not be correct (and probably isn't). However, if the raspberry status_topic does say running, then the raspberry is currently connected and presumably has published a message with the latest gpio state change.
